### ISSUE TITLE
HW2 Question

### ISSUE THREAD

**Issue by 1andDone** [StanfordVL/CS131_release#51]
Quick question on the HW2 problems from **Section 1.3** on **Non-maximum suppression**.

Everything so far makes sense except for the second step of the algorithm:

> 2. Compare the edge strength of the current pixel with the edge strength of the pixel in the positive and negative gradient directions. For example, if the gradient direction is south (theta=90), compare with the pixels to the north and south.

What I'm not understanding is when theta=90, why is the gradient direction south and not north? It seems as though theta is being measured clockwise from the positive x-axis. Why?

**Comment by brentyi** [comment]
Hi there!

The y-axis points downward in images (0,0 at top left) as opposed to upward in a standard 2D plot (0,0 at bottom left), so applying right-hand rules leaves you with clockwise rotations for positive angles. This is why positive = clockwise in Photoshop, Google Slides, etc.

Also see: https://en.wikipedia.org/wiki/Angle#Positive_and_negative_angles
